/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Beverage.CocaCola;
import Model.Beverage.Pepsi;
import Model.Beverage.SevenUP;
import Model.Beverage.Water;
import Model.Item;
import Model.MainMeals.BeefShawarma;
import Model.MainMeals.Burger;
import Model.MainMeals.ChickenShawarma;
import Model.SIdeDishs.Cheese;
import Model.SIdeDishs.FrenshFries;
import Model.SIdeDishs.OnionRings;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Vector;
import javax.swing.JSpinner;

/**
 *
 * @author alahm
 */
public class Menu extends javax.swing.JFrame {

    Vector<JSpinner> spinrers = new Vector<>();
    Vector<Item> items = new Vector<>();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIcon();
        startNew();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelHold = new javax.swing.JPanel();
        jRadio1 = new javax.swing.JRadioButton();
        jRadio2 = new javax.swing.JRadioButton();
        jRadio3 = new javax.swing.JRadioButton();
        jCheck1 = new javax.swing.JCheckBox();
        jCheck2 = new javax.swing.JCheckBox();
        jCheck3 = new javax.swing.JCheckBox();
        jCheck4 = new javax.swing.JCheckBox();
        jCheck5 = new javax.swing.JCheckBox();
        jComboBoxType = new javax.swing.JComboBox<>();
        jComboBoxTable = new javax.swing.JComboBox<>();
        jSpinnerI1 = new javax.swing.JSpinner();
        jSpinnerI2 = new javax.swing.JSpinner();
        jSpinnerI3 = new javax.swing.JSpinner();
        jSpinnerI4 = new javax.swing.JSpinner();
        jSpinnerI5 = new javax.swing.JSpinner();
        jSpinnerI6 = new javax.swing.JSpinner();
        jSpinnerI7 = new javax.swing.JSpinner();
        jSpinnerI8 = new javax.swing.JSpinner();
        jButtonOrder = new javax.swing.JButton();
        jLabelPrice1 = new javax.swing.JLabel();
        jLabelPrice2 = new javax.swing.JLabel();
        jLabelPrice3 = new javax.swing.JLabel();
        jLabelPrice4 = new javax.swing.JLabel();
        jLabelPrice5 = new javax.swing.JLabel();
        jLabelPrice6 = new javax.swing.JLabel();
        jLabelPrice7 = new javax.swing.JLabel();
        jLabelPrice8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBill = new javax.swing.JTextArea();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shawarma Neverland");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1022, 800));
        setMinimumSize(new java.awt.Dimension(1022, 800));
        setPreferredSize(new java.awt.Dimension(1022, 800));
        setResizable(false);

        jPanelHold.setMaximumSize(new java.awt.Dimension(1022, 800));
        jPanelHold.setMinimumSize(new java.awt.Dimension(1022, 800));
        jPanelHold.setPreferredSize(new java.awt.Dimension(1022, 800));
        jPanelHold.setLayout(null);

        jRadio1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadio1);
        jRadio1.setText("Chicken Shawarma");
        jRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1ActionPerformed(evt);
            }
        });
        jPanelHold.add(jRadio1);
        jRadio1.setBounds(120, 240, 150, 20);

        jRadio2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadio2);
        jRadio2.setText("Beef Shawarma");
        jRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2ActionPerformed(evt);
            }
        });
        jPanelHold.add(jRadio2);
        jRadio2.setBounds(120, 280, 130, 20);

        jRadio3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadio3);
        jRadio3.setText("Burger ");
        jRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio3ActionPerformed(evt);
            }
        });
        jPanelHold.add(jRadio3);
        jRadio3.setBounds(120, 320, 80, 20);

        jCheck1.setBackground(new java.awt.Color(255, 255, 255));
        jCheck1.setText("Water");
        jCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck1ActionPerformed(evt);
            }
        });
        jPanelHold.add(jCheck1);
        jCheck1.setBounds(120, 440, 80, 20);

        jCheck2.setBackground(new java.awt.Color(255, 255, 255));
        jCheck2.setText("Soft Drink");
        jCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck2ActionPerformed(evt);
            }
        });
        jPanelHold.add(jCheck2);
        jCheck2.setBounds(120, 480, 100, 20);

        jCheck3.setBackground(new java.awt.Color(255, 255, 255));
        jCheck3.setText("Frensh fries");
        jCheck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck3ActionPerformed(evt);
            }
        });
        jPanelHold.add(jCheck3);
        jCheck3.setBounds(120, 610, 120, 20);

        jCheck4.setBackground(new java.awt.Color(255, 255, 255));
        jCheck4.setText("Onion rings");
        jCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck4ActionPerformed(evt);
            }
        });
        jPanelHold.add(jCheck4);
        jCheck4.setBounds(120, 650, 100, 20);

        jCheck5.setBackground(new java.awt.Color(255, 255, 255));
        jCheck5.setText("Cheese");
        jCheck5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck5ActionPerformed(evt);
            }
        });
        jPanelHold.add(jCheck5);
        jCheck5.setBounds(120, 690, 100, 20);

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca-Cola", "Pepsi", "7 UP" }));
        jPanelHold.add(jComboBoxType);
        jComboBoxType.setBounds(450, 480, 110, 22);

        jComboBoxTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "22", "23", "24", "25" }));
        jPanelHold.add(jComboBoxTable);
        jComboBoxTable.setBounds(660, 220, 140, 22);

        jSpinnerI1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI1);
        jSpinnerI1.setBounds(380, 240, 60, 22);

        jSpinnerI2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI2);
        jSpinnerI2.setBounds(380, 280, 60, 22);

        jSpinnerI3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI3);
        jSpinnerI3.setBounds(380, 320, 60, 22);

        jSpinnerI4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI4);
        jSpinnerI4.setBounds(380, 430, 60, 22);

        jSpinnerI5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI5);
        jSpinnerI5.setBounds(380, 480, 60, 22);

        jSpinnerI6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI6);
        jSpinnerI6.setBounds(380, 600, 60, 22);

        jSpinnerI7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI7);
        jSpinnerI7.setBounds(380, 640, 60, 22);

        jSpinnerI8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jPanelHold.add(jSpinnerI8);
        jSpinnerI8.setBounds(380, 680, 60, 22);

        jButtonOrder.setText("ORDER");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });
        jPanelHold.add(jButtonOrder);
        jButtonOrder.setBounds(830, 320, 120, 22);

        jLabelPrice1.setText("10 RM");
        jPanelHold.add(jLabelPrice1);
        jLabelPrice1.setBounds(290, 240, 34, 16);

        jLabelPrice2.setText("12 RM");
        jPanelHold.add(jLabelPrice2);
        jLabelPrice2.setBounds(290, 280, 34, 16);

        jLabelPrice3.setText("15 RM");
        jPanelHold.add(jLabelPrice3);
        jLabelPrice3.setBounds(290, 320, 34, 16);

        jLabelPrice4.setText("2 RM");
        jPanelHold.add(jLabelPrice4);
        jLabelPrice4.setBounds(290, 440, 27, 16);

        jLabelPrice5.setText("3 RM");
        jPanelHold.add(jLabelPrice5);
        jLabelPrice5.setBounds(290, 480, 27, 16);

        jLabelPrice6.setText("4 RM");
        jPanelHold.add(jLabelPrice6);
        jLabelPrice6.setBounds(290, 610, 27, 16);

        jLabelPrice7.setText("4 RM");
        jPanelHold.add(jLabelPrice7);
        jLabelPrice7.setBounds(290, 650, 27, 16);

        jLabelPrice8.setText("2 RM");
        jPanelHold.add(jLabelPrice8);
        jLabelPrice8.setBounds(290, 690, 27, 16);

        jButton1.setText("NEW ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelHold.add(jButton1);
        jButton1.setBounds(670, 320, 120, 22);

        jTextAreaBill.setColumns(20);
        jTextAreaBill.setRows(5);
        jTextAreaBill.setBorder(null);
        jTextAreaBill.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaBill.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaBill);

        jPanelHold.add(jScrollPane1);
        jScrollPane1.setBounds(650, 390, 320, 330);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assest/background.jpeg"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(1022, 800));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(1022, 800));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1022, 800));
        jPanelHold.add(jLabelBackground);
        jLabelBackground.setBounds(-10, -10, 1030, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHold, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHold, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1ActionPerformed
        // TODO add your handling code here:
        jSpinnerI1.setEnabled(true);
        jSpinnerI2.setEnabled(false);
        jSpinnerI3.setEnabled(false);
        jSpinnerI1.setValue(1);
        jSpinnerI2.setValue(0);
        jSpinnerI3.setValue(0);
        active();
    }//GEN-LAST:event_jRadio1ActionPerformed

    private void jRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2ActionPerformed
        // TODO add your handling code here:
        jSpinnerI2.setEnabled(true);
        jSpinnerI1.setEnabled(false);
        jSpinnerI3.setEnabled(false);
        jSpinnerI1.setValue(0);
        jSpinnerI2.setValue(1);
        jSpinnerI3.setValue(0);
        active();
    }//GEN-LAST:event_jRadio2ActionPerformed

    private void jRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio3ActionPerformed
        // TODO add your handling code here:
        jSpinnerI3.setEnabled(true);
        jSpinnerI1.setEnabled(false);
        jSpinnerI2.setEnabled(false);
        jSpinnerI1.setValue(0);
        jSpinnerI2.setValue(0);
        jSpinnerI3.setValue(1);
        active();

    }//GEN-LAST:event_jRadio3ActionPerformed

    private void jCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck1ActionPerformed
        // TODO add your handling code here:
        if (jCheck1.isSelected()) {
            jSpinnerI4.setEnabled(true);
            jSpinnerI4.setValue(1);
        } else {
            jSpinnerI4.setEnabled(false);
            jSpinnerI4.setValue(0);
        }


    }//GEN-LAST:event_jCheck1ActionPerformed

    private void jCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck2ActionPerformed
        // TODO add your handling code here:
        if (jCheck2.isSelected()) {
            jSpinnerI5.setEnabled(true);
            jSpinnerI5.setValue(1);
            jComboBoxType.setEnabled(true);
        } else {
            jSpinnerI5.setEnabled(false);
            jComboBoxType.setEnabled(false);
            jSpinnerI5.setValue(0);

        }
    }//GEN-LAST:event_jCheck2ActionPerformed

    private void jCheck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck3ActionPerformed
        // TODO add your handling code here:
        if (jCheck3.isSelected()) {
            jSpinnerI6.setEnabled(true);
            jSpinnerI6.setValue(1);
        } else {
            jSpinnerI6.setEnabled(false);
            jSpinnerI6.setValue(0);
        }

    }//GEN-LAST:event_jCheck3ActionPerformed

    private void jCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck4ActionPerformed
        // TODO add your handling code here:
        if (jCheck4.isSelected()) {
            jSpinnerI7.setEnabled(true);
            jSpinnerI7.setValue(1);
        } else {
            jSpinnerI7.setEnabled(false);
            jSpinnerI7.setValue(0);
        }
    }//GEN-LAST:event_jCheck4ActionPerformed

    private void jCheck5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck5ActionPerformed
        // TODO add your handling code here:
        if (jCheck5.isSelected()) {
            jSpinnerI8.setEnabled(true);
            jSpinnerI8.setValue(1);
        } else {
            jSpinnerI8.setEnabled(false);
            jSpinnerI8.setValue(0);
        }
    }//GEN-LAST:event_jCheck5ActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // this functoin to do print for the order after                                
        // pressing order button 
        items.clear();
        boolean hasDate = false;                                                    //                                        
        LocalDate date = LocalDate.now();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm a");
        Date time = new Date();
        for (int i = 0; i < spinrers.size(); i++) {                     // this for loop for checking the order 
            if ((int) spinrers.get(i).getValue() != 0) {
                hasDate = true;
                if (i == 0) {                                                // check for chicken shawarma order  
                    items.add(new ChickenShawarma());                        //if yes it will add an object to victors  
                    items.get(0).itemQuantity((int) jSpinnerI1.getValue()); // then in this we will get the quantity from jspinerr 
                                                                               // and soo on for the rest 
                }
                if (i == 1) {
                    items.add(new BeefShawarma());
                    items.get(0).itemQuantity((int) jSpinnerI2.getValue());
                }
                if (i == 2) {
                    items.add(new Burger());
                    items.get(0).itemQuantity((int) jSpinnerI3.getValue());
                }
                if (i == 3) {
                    items.add(new Water(items.get(items.size() - 1)));
                    items.get(0).itemQuantity((int) jSpinnerI4.getValue());
                }
                if (i == 4) {
                    if (jComboBoxType.getSelectedItem().equals("Coca-Cola")) {      //this for softdrink since i 3  diffrent drinks here will check the name is equla the vaulue 
                        items.add(new CocaCola(items.get(items.size() - 1)));       //if yes it will add an object to victors  then in this we will get the quantity from jspinerr 
                        items.get(0).itemQuantity((int) jSpinnerI5.getValue());     // then in this we will get the quantity from jspinerr 
                    } else if (jComboBoxType.getSelectedItem().equals("Pepsi")) {
                        items.add(new Pepsi(items.get(items.size() - 1)));
                        items.get(0).itemQuantity((int) jSpinnerI6.getValue());
                    } else {
                        items.add(new SevenUP(items.get(items.size() - 1)));        
                        items.get(0).itemQuantity((int) jSpinnerI7.getValue());
                    }
                }
                if (i == 5) {
                    items.add(new FrenshFries(items.get(items.size() - 1)));
                    items.get(0).itemQuantity((int) jSpinnerI1.getValue());
                }
                if (i == 6) {
                    items.add(new OnionRings(items.get(items.size() - 1)));
                    items.get(0).itemQuantity((int) jSpinnerI1.getValue());
                }
                if (i == 7) {
                    items.add(new Cheese(items.get(items.size() - 1)));
                    items.get(0).itemQuantity((int) jSpinnerI1.getValue());
                }
            }
        }
        if (hasDate) {                                                              //if set date 
            double total = 0;                                                       
            int counter = 0;
            DecimalFormat df = new DecimalFormat("####0.00");                       // here start to do format for print the bill 
            String bill = "\t Shawarma Neverland\nDate: " + date + "\nTime: "          // first by set date and time 
                    + formatter.format(time) + "\nTable: " + jComboBoxTable.getSelectedItem() + "\nQTY/\tItem Name\tPrice\tAmount" // then table numebr
                    + "\n-------------------------------------------------------------------------------\n";
                            
            for (int i = 0; i < spinrers.size(); i++) {                             //this for loop for insert the order from the victor 
                if ((int) spinrers.get(i).getValue() != 0) {                                        
                    bill += items.get(counter).itemQuantity((int) spinrers.get(i).getValue())  // here we will quantity and value 
                            + "\t" + items.get(counter).itemName() + "\t"
                            + items.get(counter).itemPrice() + "\t"
                            + items.get(counter).itemTotle() + "\n";    
                    total += items.get(counter).itemTotle();                // collect the total price
                    counter++;
                }
            }
            bill += "-------------------------------------------------------------------------------\nNetSubtotal                                                                  " + total;// the total without tax
            bill += "\n-------------------------------------------------------------------------------\nSales Tax                                                                      " + df.format(total * 0.05); // the tax is 5% of the price 
            bill += "\n-------------------------------------------------------------------------------\nTotal to pay                                                                   " + df.format((total * 0.05) + total); //the final price with tax

            jTextAreaBill.setText(bill);
        } else {
            jTextAreaBill.setText("Please Select one item form the main meals");
        }
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        startNew();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JCheckBox jCheck1;
    private javax.swing.JCheckBox jCheck2;
    private javax.swing.JCheckBox jCheck3;
    private javax.swing.JCheckBox jCheck4;
    private javax.swing.JCheckBox jCheck5;
    private javax.swing.JComboBox<String> jComboBoxTable;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPrice1;
    private javax.swing.JLabel jLabelPrice2;
    private javax.swing.JLabel jLabelPrice3;
    private javax.swing.JLabel jLabelPrice4;
    private javax.swing.JLabel jLabelPrice5;
    private javax.swing.JLabel jLabelPrice6;
    private javax.swing.JLabel jLabelPrice7;
    private javax.swing.JLabel jLabelPrice8;
    private javax.swing.JPanel jPanelHold;
    private javax.swing.JRadioButton jRadio1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JRadioButton jRadio3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerI1;
    private javax.swing.JSpinner jSpinnerI2;
    private javax.swing.JSpinner jSpinnerI3;
    private javax.swing.JSpinner jSpinnerI4;
    private javax.swing.JSpinner jSpinnerI5;
    private javax.swing.JSpinner jSpinnerI6;
    private javax.swing.JSpinner jSpinnerI7;
    private javax.swing.JSpinner jSpinnerI8;
    private javax.swing.JTextArea jTextAreaBill;
    // End of variables declaration//GEN-END:variables

    private void startNew() {
        jTextAreaBill.setText("");
        items.clear();
        buttonGroup1.clearSelection();
        jSpinnerI1.setEnabled(false);
        jSpinnerI2.setEnabled(false);
        jSpinnerI3.setEnabled(false);
        jSpinnerI4.setEnabled(false);
        jSpinnerI5.setEnabled(false);
        jSpinnerI6.setEnabled(false);
        jSpinnerI7.setEnabled(false);
        jSpinnerI8.setEnabled(false);
        jSpinnerI1.setValue(0);
        jSpinnerI2.setValue(0);
        jSpinnerI3.setValue(0);
        jSpinnerI4.setValue(0);
        jSpinnerI5.setValue(0);
        jSpinnerI6.setValue(0);
        jSpinnerI7.setValue(0);
        jSpinnerI8.setValue(0);
        jComboBoxType.setEnabled(false);
        jComboBoxTable.setSelectedIndex(0);
        jComboBoxType.setSelectedIndex(0);
        jCheck1.setSelected(false);
        jCheck2.setSelected(false);
        jCheck3.setSelected(false);
        jCheck4.setSelected(false);
        jCheck5.setSelected(false);
        jCheck1.setEnabled(false);
        jCheck2.setEnabled(false);
        jCheck3.setEnabled(false);
        jCheck4.setEnabled(false);
        jCheck5.setEnabled(false);
        jRadio1.setSelected(false);
        jRadio2.setSelected(false);
        jRadio3.setSelected(false);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Assest/iconsRestaurant.png")));
    }

    private void initialize() {
        spinrers.add(jSpinnerI1);
        spinrers.add(jSpinnerI2);
        spinrers.add(jSpinnerI3);
        spinrers.add(jSpinnerI4);
        spinrers.add(jSpinnerI5);
        spinrers.add(jSpinnerI6);
        spinrers.add(jSpinnerI7);
        spinrers.add(jSpinnerI8);
    }

    private void active() {
        jCheck1.setEnabled(true);
        jCheck2.setEnabled(true);
        jCheck3.setEnabled(true);
        jCheck4.setEnabled(true);
        jCheck5.setEnabled(true);
    }
}
